
package com.example.phoneforfilm.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single chat message.
 *
 * @property id autogenerated primary key
 * @property chatId id of the conversation this message belongs to
 * @property senderId id of the contact that sent the message. Use your own user‑id for outgoing messages
 * @property text message body
 * @property timestamp epoch millis
 * @property status delivery indicator: 0 = sent, 1 = delivered, 2 = read
 * @property isDeleted whether the message is marked as deleted
 */
@Entity(tableName = "messages")
data class Message(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val chatId: Int,
    val senderId: Long,
    val text: String,
    val timestamp: Long,
    val status: Int,
    val isDeleted: Boolean = false
)
